.github/workflows/build-and-test.yml
Create an action in order for us to be able to validate the build and unit tests within the solution.
This needs to be able to run the tests against all Lambda's within the solution as part of the PR
=> TxMA-73 Create Action For Build And Test

event-processor/src/main/resources/event-processor-template.yml
Initial PR (Primarily to test my signed commits).
=> [TXMA-123] Initial SNS template

.github/workflows/build-and-test.yml, event-processing/event-processing-template.yml
We've had to make some changes to the event-process-temmplate for use
with the new secure pipelines we're trying to roll out in AWS.  The
changes made are to make them compatible with this way of thinking.
=> Updated event-processsing-template for pipeline

.github/workflows/post-merge.yml
Update working directory for docker steps
=> update working directory for docker steps

audit/audit-template.yml, event-processing/config/samconfig-event-processing.toml, event-processing/event-processing-template.yml
Update templates to make use of new SSM parameters generated by the config pipeline
=> TMA 183 config pipelines

audit/audit-template.yml, event-processing/event-processing-template.yml
add encryption on cloudwatch logs due to checkov rule
=> Fix audit message bucket logs properties property

.github/workflows/post-merge.yml, audit/audit-template.yml, event-processing/event-processing-template.yml
Update SNS publish policy to assign to new team roles
Update workflow for post merge to sign the new Lambdas 
Fix audit bucket name reference that had not been updated
=> TMA-183 Team based integration

tests/audit-tests/src/test/java/uk/gov/di/txma/audit/bdd/SNStoS3.java
Easy one - just updating the bucket name
=> Change bucket name for test

audit/audit-template.yml, event-processing/event-processing-template.yml
Created condition to determine if in build
Change the firehose buffer time from 900 to 60 seconds
=> Adjusted buffer time for firehose from 900 to 60 for build

tests/audit-tests/src/test/java/uk/gov/di/txma/audit/bdd/SNStoS3.java
Just updated the name of the bucket (again)
=> change name of bucket to match new naming

tests/audit-tests/src/test/java/uk/gov/di/txma/audit/bdd/SNStoS3.java
=> changed name again

event-processing/obfuscation/app.ts
Add basic obfuscation function code to avoid failure in testing
=> TMA-198 Add basic pass through code for obfuscation function

event-processing/obfuscation/app.ts, event-processing/obfuscation/tests/unit/app.test.ts
Investigating why the lambda does not seem to be behaving as expected
=> TNA-252 Add additional log messages

event-processing/obfuscation/app.ts, event-processing/obfuscation/tests/unit/app.test.ts, event-processing/obfuscation/tests/unit/test-helper.ts
It seems the events are coming as an array so we've updated the lambda to be able to process that as an array.
=> TMA-252 Update code to support input arrays

tests/audit-tests/build.gradle, tests/audit-tests/gradle/wrapper/gradle-wrapper.properties, tests/audit-tests/src/test/java/uk/gov/di/txma/audit/bdd/FirehoseToS3.java, tests/audit-tests/src/test/resources/Test Data/IPV/Firehose_001.json, tests/audit-tests/src/test/resources/Test Data/IPV/S3_001.json, tests/audit-tests/src/test/resources/Test Data/IPVPass/Firehose_001.json, tests/audit-tests/src/test/resources/Test Data/IPVPass/S3_001.json, tests/audit-tests/src/test/resources/Test Data/KBV/Firehose_001.json, tests/audit-tests/src/test/resources/Test Data/KBV/S3_001.json, tests/audit-tests/src/test/resources/Test Data/KBVAddress/Firehose_001.json, tests/audit-tests/src/test/resources/Test Data/KBVAddress/S3_001.json, tests/audit-tests/src/test/resources/Test Data/KBVFraud/Firehose_001.json, tests/audit-tests/src/test/resources/Test Data/KBVFraud/S3_001.json, tests/audit-tests/src/test/resources/Test Data/SPOT/Firehose_001.json, tests/audit-tests/src/test/resources/Test Data/SPOT/S3_001.json, tests/audit-tests/src/test/resources/features/IPVPass_FirehoseToS3.feature, tests/audit-tests/src/test/resources/features/IPV_FirehoseToS3.feature, tests/audit-tests/src/test/resources/features/KBVAddress_FirehoseToS3.feature, tests/audit-tests/src/test/resources/features/KBVFraud_FirehoseToS3.feature, tests/audit-tests/src/test/resources/features/KBV_FirehoseToS3.feature, tests/audit-tests/src/test/resources/features/SPOT_FirehoseToS3.feature, tests/event-processing-tests/src/test/java/uk/gov/di/txma/eventprocessor/bdd/RunAllCucumberTest.java
This updates the audit tests to use a more robust testing method (as already used in event-processing)
=> Tma 175 update audit tests

tests/audit-tests/README.md, tests/audit-tests/build.gradle, tests/audit-tests/src/test/java/uk/gov/di/txma/audit/bdd/FirehoseToS3.java, tests/audit-tests/src/test/java/uk/gov/di/txma/audit/bdd/RunAllCucumberTest.java, tests/event-processing-tests/README.md, tests/event-processing-tests/build.gradle, tests/event-processing-tests/src/test/java/uk/gov/di/txma/eventprocessor/bdd/LambdaToS3StepDefinitions.java, tests/event-processing-tests/src/test/java/uk/gov/di/txma/eventprocessor/bdd/RunAllCucumberTest.java
For testing, add readme file and make them run in parallel
=> Tma 259 add readme comments and make parallel

tests/event-processing-tests/src/test/java/uk/gov/di/txma/eventprocessor/bdd/LambdaToS3StepDefinitions.java
The loop does the same check (checks the new message has all keys in the expected message, and that the values are equal).
The function should output when a matching message is found.
=> While changing the type of loop, I did not amend the output correctly

.github/workflows/post-merge.yml
Typo in workflow prevent Dockerfile being recognised in Audit ECR stage
=> TMA-320 Correct typo in workflow

tests/audit-tests/Dockerfile, tests/audit-tests/build.gradle, tests/audit-tests/run-tests.sh, tests/event-processing-tests/Dockerfile, tests/event-processing-tests/build.gradle, tests/event-processing-tests/run-tests.sh
Update the tests to run gradle and send the tests report to the expected directory as provided by the TEST_REPORT_DIR environment variable.
=> Tma 318 update run tests

tests/event-processing-tests/src/test/java/uk/gov/di/txma/eventprocessor/bdd/LambdaToS3StepDefinitions.java
- change counter for how long to wait for firehose to a universal counter, allowing for the second search to wait the full time if not found.
- Actually invoke the empty payload
- Remove testing output
=> A few things which were missed have been added to the step function

event-processing/event-processing-template.yml
Draft PR for App Iaac. Not to be merged until App team are ready to integrate.
=> [TMA-390] Initial App Iaac

audit/audit-template.yml
Add missing variable to lambda
=> pass in environment variable for firehoseName

tests/audit-tests/src/test/java/uk/gov/di/txma/audit/bdd/FirehoseToS3StepDefinitions.java
The delimiter function puts the events on separate lines, so we need to read all the lines from the S3 bucket rather than just the first.
=> Fix reading from S3 from over multiple lines

event-processing/event-processing-template.yml
Adding DCMAW_CRI_VC_ISSUED to the performance subscription
=> [TMA-433] Add missing app event to performance subscription

event-processing/examples/service-integration-example-template.yml
Add example template for teams wishing to integrate with TxMA
=> TMA-443 - Documentation

event-processing/event-processing-template.yml
Duplicate existing IPV resources and rename for the incoming IPV CI CRI
=> TMA-568 Add resources required for the IPV CI CRI integration

event-processing/lambda/obfuscation-app.ts, event-processing/lambda/tests/test-helpers/obfuscation-helper.ts, event-processing/lambda/tests/unit/app.obfuscation.test.ts
Implemented the preferable changes, removed the OR condition. Kindly review and approve!
=> Tma 428 obfuscation changes

event-processing/lambda/models/cleansed-event.ts, event-processing/lambda/models/enriched-audit-event.ts, event-processing/lambda/services/cleansing-service.ts, event-processing/lambda/tests/test-helpers/cleanser-helper.ts, event-processing/lambda/tests/unit/app.cleanser.test.ts, event-processing/lambda/tests/unit/services/cleansing-service.test.ts
=> Tma 429 cleanser fix for re ingest

audit/lambda/models/audit-event.ts, audit/lambda/tests/test-helpers/firehoseTester-helper.ts, audit/lambda/tests/unit/app.firehoseTester.test.ts, event-processing/lambda/models/audit-event.ts, event-processing/lambda/models/enriched-audit-event.ts, event-processing/lambda/models/user-unknown-fields.interface.ts, event-processing/lambda/tests/test-events/unknown-audit-event.ts, event-processing/lambda/tests/test-helpers/cleanser-helper.ts, event-processing/lambda/tests/test-helpers/event-processor-helper.ts, event-processing/lambda/tests/test-helpers/obfuscation-helper.ts, event-processing/lambda/tests/unit/app.cleanser.test.ts, event-processing/lambda/tests/unit/app.event-processor.test.ts
=> TMA-624 Update user section of message payload

audit/audit-template.yml
=> TMA 422 remove s3 delete permission from users in audit

tests/audit-tests/docker-compose.dev.yml, tests/audit-tests/run-tests.sh, tests/audit-tests/src/test/java/uk/gov/di/txma/audit/utilities/Driver.java
detects if running in CI or locally using docker compose and uses appropriate webdriver
=> Tma 640 fix audit build pipeline v2

tests/audit-tests/run-tests.sh, tests/audit-tests/src/test/resources/features/AddressCRI_Txma.feature, tests/audit-tests/src/test/resources/features/PassportCRI_Txma.feature
=> Fixed the tests

event-processing/event-processing-template.yml
=> add new DCMAW events to fraud and performance

tests/event-processing-tests/run-tests.sh, tests/event-processing-tests/src/test/resources/features/Build_LambdaToS3.feature
attempt to mitigate access denied and add stack trace option for detailed logging
=> un-comment example and add stacktrace to gradle command

event-processing/event-processing-template.yml, event-processing/lambda/accounts-redacted-app.ts, event-processing/lambda/models/redacted-event.ts, event-processing/lambda/package.json, event-processing/lambda/redacted-app.ts, event-processing/lambda/retry-app.ts, event-processing/lambda/services/redacted-service.ts, event-processing/lambda/tests/unit/app.redacted.test.ts, event-processing/lambda/tests/unit/app.retry.test.ts, event-processing/lambda/tests/unit/services/redacted-service.test.ts, event-processing/lambda/yarn.lock
Code clean up done as JsonPath made it simpler.
=> TMA-735 Failed To Consume Event Message to S3

tests/audit-tests/run-tests.sh, tests/audit-tests/src/test/java/uk/gov/di/txma/audit/bdd/Auth_TxmaStepDefinitions.java, tests/audit-tests/src/test/java/uk/gov/di/txma/audit/pages/AUTH/SampleServiceStagingPage.java, tests/audit-tests/src/test/java/uk/gov/di/txma/audit/utilities/ConfigurationReader.java, tests/audit-tests/src/test/resources/features/Auth_Txma.feature
New feature test to test the integration between auth and TxMA
=> New feature test to test the auth to TxMA integration

event-processing/event-processing-template.yml
Removing the unused role stack
=> TMA-748 Handling Billing data pipeline code cleanup

.gitignore, audit/audit-template.yml, audit/deploy-audit.sh
prepared the infrastructure for implementing PagerDuty
=> Feature/tt2 253  implement alerts

template.yaml
fix pipeline while waiting for dev-platform to add SlackbotConfig create ability to deploy role
=> commented out chatbot config to temporarily 

.github/dependabot.yaml
Change dependency update schedule to monthly
Add custom label to version update PRs
Increase Dependabot PR limit to 10
=> Reduce noise from Dependabot

template.yaml
* Ran some linting
* Changed template description
* Removes old SNS subscription
* Swaps a KMS key
=> Cleanup template and remove old Event Processor resources

template.yaml
i thought i had merged the time change to 2 hours but i didn't. was also getting some weird merge conflict so i just re-created the branch and made the change
=> TT2-735 update alarm to 2 hours

esbuild.config.ts, template.yaml
* The Lambda functions included all the code of other Lambdas, so have updated the ES Build config and SAM template to only include the relevant handler.js file
* Reordered the Property keys of the Lambda functions to make them easier to read
=> Update ESBuild to only package relevant files

template.yaml
This reverts commit ec2a592f2667c610ed21bc9bfe5df902182789bf.
- **Ticket Number**: #[INCIDEN-698](https://govukverify.atlassian.net/browse/INCIDEN-698) :ticket:
Reverting this change as went in prematurely
[INCIDEN-698]: https://govukverify.atlassian.net/browse/INCIDEN-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> INCIDEN-698: Revert "Adding dynatrace oneagent"

template.yaml
- **Ticket Number**: [SW-259](https://govukverify.atlassian.net/browse/SW-259) :ticket:
- **Documentation Link(s)**: :books: [INCIDEN-627](https://govukverify.atlassian.net/browse/INCIDEN-627)
Currently any log retention that is set under 30 days will be set to 30 by a Lambda attached to the LZA Lambda run
- RetentionInDays changed from 7 to 30 in template.yaml
[Provide step-by-step instructions for testing the changes made in this pull request. Were there any tests you weren't able to include but would have liked to? ]
[Include any screenshots or visual representations of the changes. Delete this section if not applicable.]
- [List any related pull requests that need to be reviewed or merged alongside this one.]
- [Please provide proper documentation or update existing documentation both …
=> SW-259: Increase log group's RetentionInDays to 30

tests/integration-tests/constants/baseEvent.ts
- **Ticket Number**: #TT2-1693 :ticket:
Changed test emails to the @example.com domain
=> TT2-1693: Changing all test emails have the @example.com domain

.secrets.baseline, template.yaml
- **Ticket Number**: #[Your Ticket Number] :ticket:
- **Documentation Link(s)**: [:books: Does this relate to an ADR/RFC/Spike ticket?]
[Provide step-by-step instructions for testing the changes made in this pull request. Were there any tests you weren't able to include but would have liked to? ]
=> TT2-1863: Adding alias to all the lambdas

template.yaml
- **Ticket Number**: #[TT2-1907](https://govukverify.atlassian.net/browse/TT2-1907) :ticket:
Re adding changes in https://github.com/govuk-one-login/txma-audit/commit/ec2a592f2667c610ed21bc9bfe5df902182789bf
[TT2-1907]: https://govukverify.atlassian.net/browse/TT2-1907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TT2-1907:Adding Dynatrace OneAgent back in

template.yaml
- **Ticket Number** :ticket: : [TT2-1974](https://govukverify.atlassian.net/browse/TT2-1974)
- **Documentation Link(s)** :books: :[Confluence](https://govukverify.atlassian.net/wiki/spaces/TMA/pages/4295360647/Lambdas+across+TxMA#Repo:-txma-audit)
Add canary deployments as outlined in Confluence link
Add IaC code for canary deployments
- Confluence link will need to be updated when this is merged
[TT2-1974]: https://govukverify.atlassian.net/browse/TT2-1974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TT2-1974 Add canary deployments

template.yaml
https://govukverify.atlassian.net/browse/TT2-1911
update glue to add ms timestamp
=> TT2-1911 - add ms timestamp to glue

src/sharedServices/firehose/firehosePutRecordBatch.ts, src/sharedServices/s3/deleteS3Object.ts, src/sharedServices/s3/getS3ObjectAsStream.ts, src/sharedServices/s3/putS3Object.ts, src/sharedServices/s3/s3ChangeStorageClass.ts, src/sharedServices/s3/s3Client.ts, src/sharedServices/s3/s3FileExists.ts, src/utils/awsSdkClients.ts
- **Ticket Number**: #[TT2-1922] :ticket:
Refactor to instantiate a single instance of each client, and use it everywhere, rather than potentially creating a new client per call to the lambda.
Integration tests pass in a feature stack.
[TT2-1922]: https://govukverify.atlassian.net/browse/TT2-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TT2-1922 Externalise AWS SDK calls

.vscode/extensions.json, .vscode/settings.json, tests/Dockerfile
- update recommended extensions
- update vscode settings with typescript, linting and formatting settings
- fix dockerfile for test container so it matches https://github.com/govuk-one-login/txma-shared-signals/blob/main/tests/Dockerfile
=> Fix pipeline

package.json
lets you run `npm run tsFile path/to/file.ts`
=> npm script to run ts file

template.yaml
- **Ticket Number**: :ticket:: https://govukverify.atlassian.net/browse/SET-121
Update lambda node version to 22
=> SET-121: Update to node 22
