govuk-one-login/txma-audit

.github/workflows/post-merge.yml
We need to make sure our obfuscation function is signed to allow the code pipeline to successfully deploy
=> TMA-198 Add obfuscation function signing for deployment

event-processing/event-processing-template.yml
Add missing policies for test S3 buckets used when we are unable to integrate to Splunk
Add conditionals for the KMS policies not required for build or dev
Include the integrations for remaining CRIs (this appear to have not been pushed in a previous PR)
=> TMA-198 infrastructure for Splunk

event-processing/event-processing-template.yml, event-processing/event-processor/app.ts, event-processing/event-processor/package.json, event-processing/event-processor/services/sns-service.ts, event-processing/event-processor/services/validation-service.ts, event-processing/event-processor/tests/unit/app.test.ts, event-processing/event-processor/yarn.lock
The following PR is to resolve an issue with the Event Invoke Configuration currently used to deliver messages to SNS from our event processor Lambda. The resultant messages created by using the event invoke config contain AWS event data that we do not want to include in our auditing and analysis streams. Currently, there is no means by which to specify RAW message delivery as with other services. As such, we have removed the Event Invoke configuration and instead use the AWS SDK to call SNS from within the Lambda.
=> TMA-198 Update Event Processing Lambda to Send to SNS from in code

event-processing/event-processing-template.yml
WHAT:
Provide the HMAC secret as a parameter for the Obfuscation function.
Provide a Role for Auth to be able to assume to read the secret value for the HMAC.
WHY:
We need to provide a secret used for encryption within the obfuscation function. Secrets manager provides this functionality without us needing to expose the secret or store externally to AWS.
Auth need to use the same HMAC secret for their encryption in order to avoid issues with multiple sources pushing data using different encryption secrets.
=> TMA-249 Provide Obfuscation Secret

event-processing/event-processor/models/audit-event-unknown-fields.ts, event-processing/event-processor/models/audit-event.ts, event-processing/event-processor/tests/test-events/unknown-audit-event.ts, event-processing/event-processor/tests/unit/app.test.ts, event-processing/obfuscation/models/audit-event.ts, event-processing/obfuscation/models/obfuscated-event.ts, event-processing/obfuscation/tests/unit/test-helper.ts
Due to the upcoming changes to the ADR: https://github.com/alphagov/digital-identity-architecture/pull/175, 
we need to update our Lambda models to reflect the updated data dictionary.
This includes adding the new field 'component_id' updating the 'request_id' field to be 'govuk_signin_journey_id' and correctly handling the 'service_name' field.
=> TMA-269 ADR payload update

event-processing/event-processor/app.ts, event-processing/event-processor/services/enrichment-service.ts, event-processing/event-processor/services/sns-service.ts, event-processing/event-processor/tests/unit/app.test.ts
Update the SNS service to populate the SNS publish input with message attributes used for filtering.
Also update to use the 'IAuditEvent' model when passing between services and use 'PublishInput' interface when defining the SNS payload
=> TMA-252 SNS message attributes

event-processing/event-processing-template.yml
Update the secretsmanager:GetSecretValue to be for the role used by the Lambda instead of the account.
=> TMA-286 Provide access to secret for obfuscation role

.github/workflows/post-merge.yml, tests/audit-tests/Dockerfile, tests/audit-tests/run-tests.sh, tests/event-processing-tests/Dockerfile, tests/event-processing-tests/run-tests.sh
The pen testing has resulted in the following comment made: 
_'As I am going through the findings I have noticed that the docker container seems to be running as root on di-txma-audit-main/tests/event-processing-tests/Dockerfile and di-txma-audit-main/tests/audit-tests/Dockerfile. As discussed on the call this afternoon, it is advisable to add USER directive in dockerfile config to limit privileges an application requires to run.  This way we can reduce the attack surface without (hopefully) breaking successful deployment.'_
As such, we have added a user directive to our Dockerfile.
Can we confirm this is all that is needed? I'm not a Linux/Docker expert.
=> TMA-320 Update docker files to set user directive (Pen testing outcome)

event-processing/event-processor/models/audit-event-unknown-fields.ts, event-processing/event-processor/models/audit-event.ts, event-processing/event-processor/models/user-unknown-fields.interface.ts, event-processing/event-processor/tests/test-events/unknown-audit-event.ts, event-processing/event-processor/tests/unit/app.test.ts, event-processing/obfuscation/models/audit-event.ts, event-processing/obfuscation/services/obfuscation-service.ts, event-processing/obfuscation/tests/unit/app.test.ts, event-processing/obfuscation/tests/unit/test-helper.ts
Due to another change to the ADR we need to update the field placement of the following fields:
- session_id
- govuk_signin_journey_id
- persistant_session_id
The fields have now moved to the user sub-object.
Unit tests have been updated to reflect the changes.
=> TMA-339 Ipdate event fields for session_id, govuk_signin_journey_id and persistant_session_id

tests/event-processing-tests/build.gradle, tests/event-processing-tests/src/test/java/uk/gov/di/txma/eventprocessor/bdd/LambdaToS3StepDefinitions.java, tests/event-processing-tests/src/test/resources/features/LambdaToS3.feature
This fixes two bugs:
1. Cloudwatch not finding all logs from the lambda
To do this, the lambda is called synchronously and we can then directly get the logs being sent to Cloudwatch without calling Cloudwatch directly. 
2. Searching the S3 buckets sometimes searches the wrong files
To do this, it now searches through the latest two files every 10 seconds for 100 seconds until the correct file is found. (If it is the second runthrough - i.e. it's already searched one S3 bucket for enough time - then it will not repeat the waiting and just check the bucket once).
=> Tma 313 fix bugs

tests/event-processing-tests/src/test/java/uk/gov/di/txma/eventprocessor/bdd/LambdaToS3StepDefinitions.java, tests/event-processing-tests/src/test/resources/Test Data/FRAUD_expected.json, tests/event-processing-tests/src/test/resources/Test Data/FRAUD_expected_random.json, tests/event-processing-tests/src/test/resources/Test Data/PERF_expected.json, tests/event-processing-tests/src/test/resources/Test Data/PERF_expected_random.json, tests/event-processing-tests/src/test/resources/Test Data/auth_update_client_request_error.json, tests/event-processing-tests/src/test/resources/Test Data/random_event.json, tests/event-processing-tests/src/test/resources/features/LambdaToS3.feature
1. Added 2 additional scenarios for subscription. One for positive case where an event name common for FRAUD and PERF appear in the output an the second one is that we dont expect a random event name appear in any of FRAUD or PERF.
2. Removed excess examples because we are testing the SNS functionality rather than individual lambda functionality
3. updated the expected file name for scenario: "Checking the filter sends "RANDOM_EVENT" to neither Fraud, nor Performance"
4. Moving searching the S3 code to a function so that it can be called for both scenarios.
=> Tma 301 subscription scenarios 02

tests/event-processing-tests/src/test/resources/Test Data/LAMBDA_ADDITIONAL_FIELD.json, tests/event-processing-tests/src/test/resources/Test Data/LAMBDA_MISSING_EVENT_NAME.json, tests/event-processing-tests/src/test/resources/Test Data/LAMBDA_MISSING_TIMESTAMP.json, tests/event-processing-tests/src/test/resources/Test Data/LAMBDA_THROUGH_TO_S3.json, tests/event-processing-tests/src/test/resources/Test Data/auth_update_client_request_error.json, tests/event-processing-tests/src/test/resources/Test Data/random_event.json
govuk_signin_journey_id, session_id and persistent_session_id have been moved to the user field in accordance to https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0023-crossteam-audit-and-analysis-eventmessage-payload.md
=> Update input files to match the schema

tests/event-processing-tests/build.gradle, tests/event-processing-tests/src/test/java/uk/gov/di/txma/eventprocessor/bdd/LambdaToS3StepDefinitions.java
At the moment, the report does not give much information about why the tests fail.
This PR adds the feature/scenario names to the report, as well as providing a reason why it fails.
=> Tma 352 make report more helpful

tests/event-processing-tests/build.gradle, tests/event-processing-tests/run-tests.sh, tests/event-processing-tests/src/test/resources/features/Build_LambdaToS3.feature, tests/event-processing-tests/src/test/resources/features/Staging_LambdaToS3.feature
Add in tagging so that we can distinguish which environment we are running tests through.
=> Tma 256 add tagging so works in staging

tests/audit-tests/Dockerfile, tests/audit-tests/run-tests.sh, tests/event-processing-tests/Dockerfile, tests/event-processing-tests/run-tests.sh
Remove USER declaration for docker file. We have been advised from the Dev platform team this unnecessary and will cause other issues in how they intended this to work.
Put the mock report back in as the dev platform team need to discuss permissions we need to use for testing. currently the environment cannot run our tests as they have limited permissions on the docker image role.
Add logging to notify if test report has successfully generated
=> TMA-318 Update Test Scripts

tests/audit-tests/build.gradle
This will fix the tagging, and coincidentally, stop the tests running (which is intentional) until the features are tagged
=> Fix incorrect tagging for audit

tests/event-processing-tests/src/test/resources/Test Data/FRAUD_S3_EXPECTED.json, tests/event-processing-tests/src/test/resources/Test Data/FRAUD_expected.json, tests/event-processing-tests/src/test/resources/Test Data/FRAUD_expected_random.json, tests/event-processing-tests/src/test/resources/Test Data/LAMBDA_ADDITIONAL_FIELD.json, tests/event-processing-tests/src/test/resources/Test Data/LAMBDA_MISSING_EVENT_NAME.json, tests/event-processing-tests/src/test/resources/Test Data/LAMBDA_MISSING_TIMESTAMP.json, tests/event-processing-tests/src/test/resources/Test Data/LAMBDA_THROUGH_TO_S3.json, tests/event-processing-tests/src/test/resources/Test Data/auth_update_client_request_error.json, tests/event-processing-tests/src/test/resources/Test Data/random_event.json
To keep the tests up to date with the latest schema, we need to include user_id in the test data
=> Add user_id to input

tests/event-processing-tests/build.gradle, tests/event-processing-tests/src/test/java/uk/gov/di/txma/eventprocessor/bdd/LambdaToS3StepDefinitions.java, tests/event-processing-tests/src/test/resources/features/Build_LambdaToS3.feature
In the step definitions:
- removed unused imports
- use requestID to track the specific lambda invoke
- remove checking no error message step
- combine checking for ERROR and WARN
- Add function to send empty message (this will force the logs to be send if the error discovered before occurs)
- Add function to search cloudwatch logs
build.gradle:
-remove unused dependency
feature:
- remove cloudwatch search for no error
- reword search for ERROR and WARN so they can use the same step definition
=> Update tests to search cloudwatch as a backup search

audit/audit-template.yml, event-processing/event-processing-template.yml
Update the LogGroupName reference of the SubscriptionFilter resources to use the log group cloudformation resource name
=> TMA-366 Add Delimiter log group integration to CSLS

tests/audit-tests/src/test/java/uk/gov/di/txma/audit/bdd/FirehoseToS3StepDefinitions.java, tests/audit-tests/src/test/resources/features/FirehoseToS3.feature, tests/event-processing-tests/build.gradle, tests/event-processing-tests/src/main/java/Cleanup.java, tests/event-processing-tests/src/main/java/uk/gov/di/txma/eventprocessor/Cleanup.java, tests/event-processing-tests/src/test/java/uk/gov/di/txma/eventprocessor/bdd/LambdaToS3StepDefinitions.java
Right now, if there are over 1000 objects in an S3 buckets, only the first 1000 are checked for the latest objects. However, the latest objects will not be in this batch. Also, if there are no events, the step definitions fail.
To account for this, we will search all the batches for the latest keys. Also, in the event-processor test, we will empty the bucket after each successful run through of the test to save on storage.
=> Tma 424 fix s3 listing limit

audit/audit-template.yml
For putRequest metrics, we need to enable request metrics.
Then the alarm checks how many messages were sent over the previous day and, if there were none, sends an alarm.
=> Get request metrics from the S3 bucket and set alarm based on this

audit/audit-template.yml, event-processing/event-processing-template.yml
The conditions were confusing and slightly wrong. 
These have been renamed and corrected.
Some uses of the conditions were not actually used (always true or false)
Two policies relating to the conditions are never used
=> Tidy up and fix conditions and their usages

event-processing/lambda/models/cleansed-event.ts, event-processing/lambda/services/cleansing-service.ts, event-processing/lambda/tests/test-helpers/cleanser-helper.ts, event-processing/lambda/tests/unit/app.cleanser.test.ts
To comply with a performance request, extensions.evidence.validityScore should be added to the performance index - i.e. not be removed by the cleanser function.
=> Tma 483 add additional field in cleanser

tests/event-processing-tests/src/test/java/uk/gov/di/txma/eventprocessor/bdd/LambdaToS3StepDefinitions.java
When using `==""` it was not correctly checking if the string was empty and was not behaving as expected.
=> TMA-484 Correct check for empty string

tests/event-processing-tests/src/main/java/uk/gov/di/txma/eventprocessor/Cleanup.java
By leaving one object in each bucket, the SDK should be able to not error in the same way and wait rather than stopping the test.
=> TMA-487 Leave one object in each bucket

audit/audit-template.yml, event-processing/event-processing-template.yml
Allow the source buckets for CSLS log shipping to allow for cross account policies.
'RestrictPublicBuckets' only allows for principals within the same account.
=> Allow Cross Account Bucket Access

tests/audit-tests/src/test/resources/features/AddressCRI_Txma.feature
As this test is failing while the stub has been changed, it should be switched off until the cross-team dependancy has been fixed
=> Turn off test for address

event-processing/event-processing-template.yml
We have started getting an error of Configuration overlap when trying to deploy some S3 buckets in staging. Looking it up, it seems to be due to having notifications of the same event type. The only notifications for these buckets are for the CSLS logs (not that we have managed to get the logs through yet).
This will turn off those notifications to try and assess the issue
=> Turn off CSLS notifications to temporarily try to fix pipeline breaking

event-processing/event-processing-template.yml
This uses the reingest lambda to monitor the failures for CSLS rather than the S3 bucket - this is to prevent the notification events being duplicated.
=> TMA-640 Add log subscription to CSLS to allow them to monitor our failed events

event-processing/lambda/models/cleansed-event.ts, event-processing/lambda/services/cleansing-service.ts, event-processing/lambda/tests/test-helpers/cleanser-helper.ts, event-processing/lambda/tests/test-helpers/obfuscation-helper.ts, event-processing/lambda/tests/unit/app.cleanser.test.ts, event-processing/lambda/tests/unit/services/cleansing-service.test.ts, tests/event-processing-tests/src/test/resources/Test Data/App/perf_s3_expected.json, tests/event-processing-tests/src/test/resources/Test Data/AuthAccountMgmt/perf_s3_expected.json, tests/event-processing-tests/src/test/resources/Test Data/AuthOIDC/perf_s3_expected.json, tests/event-processing-tests/src/test/resources/Test Data/IPV/perf_s3_expected.json, tests/event-processing-tests/src/test/resources/Test Data/IPVCI/perf_s3_expected.json, tests/event-processing-tests/src/test/resources/Test Data/IPVPass/perf_s3_expected.json, tests/event-processing-tests/src/test/resources/Test Data/KBV/perf_s3_expected.json, tests/event-processing-tests/src/test/resources/Test Data/KBVAddress/perf_s3_expected.json, tests/event-processing-tests/src/test/resources/Test Data/KBVFraud/lambda_through_to_s3.json, tests/event-processing-tests/src/test/resources/Test Data/KBVFraud/perf_s3_expected.json, tests/event-processing-tests/src/test/resources/Test Data/SNSFilterTests/perf_expected.json, tests/event-processing-tests/src/test/resources/Test Data/SNSFilterTests/perf_expected_random.json, tests/event-processing-tests/src/test/resources/Test Data/SPOT/perf_s3_expected.json, tests/event-processing-tests/src/test/resources/Test Data/lambdaToCloudwatchTests/perf_s3_expected.json
This is to keep in line with the new decision authorised by IA to allow all events to be traced back to the original event - and hence, to the original client_id
=> Tma 643 add client id and journey id to performance

tests/event-processing-tests/src/test/resources/features/Build_LambdaToS3.feature
some tests in event processing are broken. those tests have been removed so we can continue adding new events to splunk
=> comment out broken tests

.github/dependabot.yaml
Have dependabot ignore AWS SDK updates as these are quite noisy, and sometime they break our builds.
=> Ignore AWS SDK updates

template.yaml
The new temporary and permanent buckets used for encryption work need lifecycle rules so we can automatically delete data tagged as test data. We previously had this set up for the existing audit bucket.
=> Add rule to delete test data automatically

template.yaml
* Swap S3 logging to S3 logs bucket in infra stack
* Add DeletionPolicy of "Retain" to existing logs buckets. These can then be deleted from the template in a subsequent PR, and then can be cleaned up outside of any IaC deployments.
=> Swap to use shared s3 logs bucket from core infra stack

template.yaml
The buckets are not empty, but have a deletion policy that means they can be removed from the template and cleared out manually after the deployment.
=> Remove unused log buckets

template.yaml
It looks as if the previous condition on the MessageBatchBucket that set up some queue configuration was malformed, so this is an attempt to fix it. I couldn't see a way to get multiple entries in a YAML list to have a condition, so I just added it twice.
=> Fix malformed config in MessageBatchBucket

template.yaml
There is no enforced dependency on the S3 Buckets to exist in the queue policy. This might be causing the failures in the build account we are seeing.
=> Add dependency on Audit buckets to Queue policy

template.yaml
Audit files are always in a subfolder of the audit batch bucket, so we need to be able to write to the equivalent location for the permanent bucket when encrypting.
This problem originally surfaced when trying to run integration tests for ticf-integration in `build`
=> Allow encrypt function to write to subfolders

template.yaml
This has been found to not be necessary, following discussions with Cyber and existing members of the TxMA team, and clashes with our need to notify the encrypt lambda.
=> Remove ObjectCreated event to CSLS link.

template.yaml
This PR swaps the SNS subscription to the new Firehose delivery stream. So all the new resources will now be in use. A follow up PR will then be raised to delete the old resources.
=> Enable feature branch deployments - Part 5

template.yaml
* Removes old resources that are no longer used.
* Fixes an instance where the new delivery stream was referencing the old IAM role - causes no issues since the new role and the old role had the same permissions
* It also removes the bucket policies on the Temporary and Permanent buckets - these were also referencing the old Encrypt Lambda ARNs. Thought this would have caused an issue. However, the permissions the Bucket policy provided exist on the Lambda function role anyway. Assume these policies are leftover from a time where things were a bit different, seeing as the permissions reference a delete which no longer happens. Thought it best to remove the policies so the permissions are only defined in one place
=> Enable feature branch deployments - Part 6

template.yaml
* Adds new SNS subscription to the new Event Processor topic - this topic is currently not active, but needs to be there until we swap it to active in the Event Processor repo
=> Add new Event Processor SNS subscription

template.yaml
- A Dead Letter queue, `AuditMessageDeliveryStreamSubscriptionDeadLetterQueue`, for the `AuditEventDeliveryStreamSubscription` to ensure that if SNS fails to publish to firehose, their events will not be lost 
- An alarm attached to this DLQ, with slack integration, to ensure that if the number of messages on the DLQ is > 0 a message is sent to Slack
=> TT2-736 audit add dlq and alarm to sns subscription

template.yaml
* Wires up OK status for Pager Duty alerts
* Removes Pager Duty alert from success percentage alarm
* Did some re-ordering so things are alphabetical
=> Update alarms to wire up PagerDuty OK status

template.yaml
* Adds a Dead Letter Queue to the Processing failed queue - just to make it a bit more robust
* Adds alarm when an item lands on the DLQ
* Renamed the original queue (it was also called a dlq) to avoid confusion
=> Rename audit message failed processing queue, and add dlq

template.yaml
The managed policy on these functions is not required. It gives kinesis:* permissions. Which is a different service to firehose. The required permissions are attached to the role separately.
=> Remove unused Kinesis policy

template.yaml, yarn.lock
Removes some lifecycle rules from the audit buckets that appear in production. These were probably copied from the TxMA 2 bucket (which only appears up to staging).
=> Remove unused auto test lifecycle rules

template.yaml
* Adds some missing `TreatMissingData` properties so it's explicit how the alarm treats missing data
* Update this property for some alarms from `notBreaching` to `ignore` - the reasoning here being that the metrics the alarms are monitoring may return to acceptable levels over a period of time, so we want to maintain the alarm state whenever there is missing data. This means that the alarm will only change state when it has data to read (not when it encounters missing data).
* Moves alarm properties into alphabetical order
=> Tidy alarms - Update how missing alarm data is treated

.secrets.baseline, template.yaml
[TT2-929](https://govukverify.atlassian.net/browse/TT2-929)
**Testing**
Once the audit stack with the changes got deployed, deleted the stack TT2-929 stack manually.
Once the stack was deleted, the corresponding empty S3 MessageBucket and PermanentMessageBucket could still be seen, as expected
[TT2-929]: https://govukverify.atlassian.net/browse/TT2-929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TT2-929: Add Retain policy to buckets

template.yaml
Add alarm for old messages on queue used by S3CopyAndEncryptFunction Add metric filter and alarm for S3CopyAndEncryptFunction
- **Ticket Number** :ticket: : [TT2-1974](https://govukverify.atlassian.net/browse/TT2-1974)
- **Documentation Link(s)** :books: :[Confluence](https://govukverify.atlassian.net/wiki/spaces/TMA/pages/4295360647/Lambdas+across+TxMA#Repo:-txma-audit)
Add alarms as outlined in Confluence link. A separate PR will be needed to complete 1974 by adding canary deployment once we are happy with the alarm
- Add alarm for old messages on queue used by S3CopyAndEncryptFunction
- Add metric filter and alarm for S3CopyAndEncryptFunction
- Add metric filter and alarm for AuditMessageDelimiterFunction
- Add metric filter and alarm for AuditMessageFirehoseReingestFunction
- Add …
=> TT2-1974 Add alarms

template.yaml
- https://govukverify.atlassian.net/browse/DPT-936
- https://govukverify.atlassian.net/browse/DPT-928
To help with https://govukverify.atlassian.net/browse/DPT-928, https://govukverify.atlassian.net/browse/DPT-936 allows the audit store to search through top level `txma` field in the audit events. 
This does not apply to the SAL tables
=> DPT-936: add txma top level field to athena

.github/dependabot.yaml, .github/workflows/build-test-package.yaml, package.json
BAU but related to https://govukverify.atlassian.net/browse/DPT-1645
Reduce dependabot spam
Update dependabot config to group types of updates and only run weekly
Fix in package.json for running the github actions update script
Changed the build action to not run linting and test steps if the npm install fails. Only really an issue when dependabot updates don't work
=> Bau bot updates

template.yaml
- **Ticket Number**: :ticket:: https://govukverify.atlassian.net/browse/DPT-2138
Add filters to AWS CloudWatch subscriptions to stop AWS Lambda system logs and messages with level "Debug", & "Trace" from being forwarded on to Splunk.
Check the logs in CloudWatch And compare in Splunk. Lambda System logs (START, END, REPORT messages) should not be visible in splunk. We don't currently have any messages at Debug or Trace level.
=> DPT-2138 Add Aws log filters

tests/constants/baseEvent.ts, tests/e2eTests/testSuites/eventProcessedByFirehoseAuditE2e.spec.ts, tests/integrationTests/testSuites/eventProcessedByFirehoseAudit.spec.ts
- **Ticket Number**: :ticket:: https://govukverify.atlassian.net/browse/DPT-2262
Add txma meta data for successful/unsuccessful enrichment to audit tests in build and staging
Run npm run test:integration in the audit-build account
Run npm run test:e2e in the audit staging account
We can see the meta data value being stored in the audit store in staging
=> Dpt 2262 - add meta data to audit auto tests
